### ISSUE TITLE
using more 'complicated' commands

### ISSUE THREAD

**Issue by matfranczyk** [lambdalisue/vital-Whisky#15]
Hi, I cannot execute commands using pipes and/or file redirection.

E.g. like 'ls -la | grep -i pattern > redirect.file'

Ps.It related with 'Job' feature You've provided.

Is there a way to do so? 
Thanks in advance :)

**Comment by lambdalisue** [comment]
I'm sorry but I have no idea what are you talking about. Which command? Why pipe?

This is a module library of [vital.vim](https://github.com/vim-jp/vital.vim). I guess you are posting an issue to a wrong repository.

**Comment by matfranczyk** [comment]
Hi,
Sorry for misleading question. Please take a look 👍  it's related with 'System.Job' library

        let job = s:Job.start(split(**'ls -la | grep -i pattern > redirect.file'**)], {
                      \ 'on_stdout': function('on_stdout'),
                      \ 'on_stderr': function('on_stderr'),
                      \ 'on_exit': function('on_exit'),
                      \ })

**Comment by lambdalisue** [comment]
Now I got. Well the command is executed directly so you cannot use pipe. If you need to use shell feature, use `/bin/sh` or whatever like.

```
let job = s:Job.start(['/bin/sh', '-c', 'ls -la | grep -i pattern > redirect.file'], ...)
```

**Comment by matfranczyk** [comment]
Thanks a lot :) Whiskey it's really good vital' s enhancement
