### ISSUE TITLE
exit_status will not have valid value, when segmentation fault occurs (nvim = 0 | vim = -1)

### ISSUE THREAD

**Issue by matfranczyk** [lambdalisue/vital-Whisky#19]
Hi @lambdalisue,
I've noticed that exit_status that is passed to 'on_exit' method has value set to 0, which is recognized in unix based systems as 'exit success' when segmentation fault (cored dump) is generated.

for nvim we have '0' value for exit_status
for vim we have '-1' for the same case
bash shows '139' error value in my environment for Segmentation fault (core dumped)

could you help with it? 
I'm attaching
- simple cpp file that could be compiled (g++ test.cpp) and execution triggers 'segmentation fult' 
- issue.vim file with vimL implementation that calles 'a.out' by using your plugin - when binary ends the exit status is echomsg'ed.

[issue.segmentation.fault.zip](https://github.com/lambdalisue/vital-Whisky/files/2737795/issue.segmentation.fault.zip)

**Comment by matfranczyk** [comment]
@lambdalisue please help :) think that it's very important issue, thanks in advance

**Comment by lambdalisue** [comment]
Sorry for late. Well, it sounds like a bug on Vim and Neovim. `System.Job` does not touch the `exit_status` in `on_exit` method.

https://github.com/lambdalisue/vital-Whisky/blob/master/autoload/vital/__vital__/System/Job/Vim.vim#L63
https://github.com/lambdalisue/vital-Whisky/blob/master/autoload/vital/__vital__/System/Job/Neovim.vim#L59

So I suggest you to report this issue on Vim and Neovim itself.
